name: testing

on: pull_request

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: python install
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Testing
        run: poetry run python -m unittest discover tests/open_data_parser/
